# Generated by Django 3.0.8 on 2020-10-10 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.TextField(null=True)),
                ('semester', models.IntegerField(null=True)),
                ('sgpa', models.FloatField(null=True)),
                ('paid', models.IntegerField(null=True)),
                ('payable', models.IntegerField(null=True)),
                ('due', models.IntegerField(null=True)),
                ('others', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
