# Generated by Django 3.0.8 on 2020-10-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201011_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bldgrp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mname',
            field=models.TextField(null=True),
        ),
    ]
