# Generated by Django 3.0.8 on 2020-10-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201011_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sgpa',
            field=models.FloatField(null=True),
        ),
    ]
