# Generated by Django 3.0.8 on 2021-06-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20201011_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sgpa',
            new_name='cgpa',
        ),
    ]
